name: CI Pipeline for Chatbot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        echo "🧪 Running tests..."
        python test_app.py
    
    - name: Verify imports
      run: |
        echo "🔍 Checking imports..."
        python -c "import streamlit; print('✅ Streamlit works')"
        python -c "import wikipedia; print('✅ Wikipedia works')" 
        python -c "import auth; print('✅ Auth system works')"
        python -c "import main; print('✅ Main app works')"
    
    - name: Success!
      run: |
        echo "🎉 ALL TESTS PASSED!"
        echo "🚀 Your chatbot is working perfectly!"
        echo "👉 Deploy manually: https://share.streamlit.io"
